spring:

  application:
    name: Bootstrap Spring Boot

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password:

  error:
    path: /error2